version: '3'
services:
  mariadb-photos:
    build: .
    image: mariadb-photos:test
    command: npm run prod
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      MARIA_HOST:
      MARIA_PORT:
      MARIA_USER:
      MARIA_PASSWORD:
      MARIA_DATABASE:
      REDIS_HOST:
      REDIS_PORT:
      REDIS_URL:
      REDIS_PASSWORD:
